### ISSUE TITLE
Another Language - a wish

### ISSUE THREAD

**Issue by moskbnea** [pixley/pf2e-statblock-for-obsidian#10]
Hello, thank you very much for your program.
I have a big request. I don't play Pathfinder 2 in English. I believe the getClassForTraitTag function only has the English tags, right? Would it be possible to code the settings options in "pf2e-statblock-for-obsidian"? So that the user can enter the tags in their own language? Now all tags are in red if they are not English.

**Comment by pixley** [comment]
Thanks for reaching out!  I really wasn't expecting any interest from folks using other languages, but I'd be happy to add internationalization support.

**Comment by pixley** [comment]
Version 3.0.2 has gone up with internationalization support.  If your language is on the supported list, I hope it works great for you.  If not, feel free to open a new issue for your specific language.

I am aware that your original ask was to add the trait translations directly as configuration, but I didn't want to get into a situation where folks were having to do redundant work.  Makes more sense to have folks poke me.

Enjoy!

**Comment by moskbnea** [comment]
Thank you very much. It's great.Wonderful. Am 07.05.24, 22:29 schrieb Tyler Pixley ***@***.***>:

   
  Closed #10 as completed.
