### ISSUE TITLE
Spanish support

### ISSUE THREAD

**Issue by GregoCatalan** [pixley/pf2e-statblock-for-obsidian#13]
Hi! I'd like to help with the Spanish support of the plugin. 

If you have the list of tags I can provide you the Spanish translation of each one, or let me know how you want to achieve this and I'll do my best to provide you the info.

**Comment by GregoCatalan** [comment]
I just checked the code and there is the Spanish version, it is just not part of the list of languages. Thanks for your work!

**Comment by pixley** [comment]
Oh.  Huh.  Don't know how I missed putting that in the readme.  I'll fix that.  I appreciate your willingness to help out!
