### ISSUE TITLE
Action icons do not work for Chinese and a question about the indent.

### ISSUE THREAD

**Issue by Ellldin** [pixley/pf2e-statblock-for-obsidian#14]
Hello Pixley, thank you for your work!
I am a Chinese user, and I noticed that when I input information in Chinese, the action icons do not display properly.
Here is a comparison between English and Chinese:
```
```pf2e-stats
# Test
## Test 1
---
**测试** `[one-action]` 测试测试测试
**Test** `[one-action]` Testtest.
````
![image](https://github.com/user-attachments/assets/92659cdc-51dc-4549-b640-6e88312405cb)
---
I also have a question for the indent you used here:
![image](https://github.com/user-attachments/assets/192bad9d-d826-408d-9ac5-e0c477a56b10)
I tried to indent using tabs and four spaces, but neither worked. I can only achieve indentation by copying and pasting the symbols you used in the example. I'm not very familiar with coding. Do you have any idea what might be going wrong?

**Comment by pixley** [comment]
Hi Ellldin!  Thanks for letting me know about the action icons.  I'll look into that.  As for the indentation, tabs are indeed correct.  Taking a look at the Unicode specification, it seems like the issue may be that tabs don't have a specified width in East Asian fonts.  Based on my hazy recollection from university, Japanese uses a single space for paragraph indentation.  Is it the same in Chinese, or is there some other preferred indentation standard?

**Comment by Ellldin** [comment]
> Hi Ellldin! Thanks for letting me know about the action icons. I'll look into that. As for the indentation, tabs are indeed correct. Taking a look at the Unicode specification, it seems like the issue may be that tabs don't have a specified width in East Asian fonts. Based on my hazy recollection from university, Japanese uses a single full-width space for paragraph indentation. Is it the same in Chinese, or is there some other preferred indentation standard?

Hi Pixley, thank you so much for your help. The icons are working now, and I found out that I can use either one tab plus one space or four spaces for indentation. even one tab alone is still not working, but everything is fine!
