### ISSUE TITLE
Add font sizing

### ISSUE THREAD

**Issue by pixley** [pixley/pf2e-statblock-for-obsidian#4]
Support some form of font resizing for accessibility.

**Comment by pixley** [comment]
### Research Note

Text size is derived from a user setting.  The CSS variables can be found on the [Headings](https://docs.obsidian.md/Reference/CSS+variables/Editor/Headings) and [Typography](https://docs.obsidian.md/Reference/CSS+variables/Foundations/Typography) pages.  Probably will need to be selective as to which header's size to bind the Title and Level text.

**Comment by pixley** [comment]
Resolved in 1.2.1.

**Comment by RavenRaconteur** [comment]
Hello! The statblocks don't seem to be responding to my text size setting. What could I do to fix this?
