### ISSUE TITLE
Settlement size trait

### ISSUE THREAD

**Issue by RavenRaconteur** [pixley/pf2e-statblock-for-obsidian#9]
Settlement traits such as "town", "village", "city", etc. aren't being colored properly when added to the statblocks. Should be green similar to a creature size. For consistency's sake, it would be cool to see this tweaked. Thanks!

**Comment by pixley** [comment]
Ah, good find!  I'll get to looking into that.

**Comment by RavenRaconteur** [comment]
awesome, thanks! you da man
